site_name: Mekanism Docs
nav:
  - Home: index.html
  - Systems: systems.html
  - Configs: configs.html
not_in_nav: |
  /configs
  /multiblocks
  /systems
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - smarty
