site_name: Mekanism Docs
nav:
  - Home: index.md
  - Systems: systems.md
  - Configs: configs.md
not_in_nav: |
  /configs
  /multiblocks
  /systems
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - smarty
